shebang := if os() == 'windows' { 'pwsh.exe' } else { '/usr/bin/env pwsh' }
set shell := ["pwsh", "-c"]
set windows-shell := ["pwsh.exe", "-NoLogo", "-Command"]
set dotenv-load := true
set script-interpreter := ["pwsh.exe", "-NoLogo", "-Command"]
set dotenv-filename	:= ".env"
set unstable
# set dotenv-required := true
export JUST_ENV := "just_env" # WARN: this is also a method to export env var. 
_default:
    @just --list

alias b := build
[no-cd]
build:
    npm install && npm run build
    
alias r := run
default_args := ''
[no-cd]
run args=default_args:
    npm run {{args}}

alias sv := serve
[no-cd]
serve *args:
    npm run serve {{args}}

alias fmt := format
format:
    # format plesase. could also run rfmt

alias t := test
test:
    # test.

alias w := watch
watch:
    # watch, mostly spin up an application e.g. `r r`-> read log by less/bat/ov/tailspin

alias dep := deploy
deploy:
    # deploy ...like at least commit and push to remote first.

alias sk := seek
seek:
    # seek ...what? maybe reference to other?

[script]
script:
    Write-Host "this is in powershell, without shebang syntax"

alias ei := edit-in-ide
[no-cd]
edit-in-ide *args:
    code . {{args}}
