shebang := if os() == 'windows' { 'pwsh.exe' } else { '/usr/bin/env pwsh' }
set shell := ["nu", "-c"]
set windows-shell := ["pwsh.exe", "-NoLogo", "-NoProfile","-Command"]
set dotenv-load := true
set script-interpreter := ["pwsh.exe", "-NoLogo", "-NoProfile","-Command"]
set dotenv-filename	:= ".env"
set unstable
set fallback
# set dotenv-required := true
export JUST_ENV := "just_env" # WARN: this is also a method to export env var. 
_default:
    @just --list

alias b := build
[no-cd]
build:
    uv build . # probably.

alias r := run
default_args := 'args here'
run args=default_args:
    @Write-Host {{default_args}} -ForegroundColor Red

alias fmt := format
format:
    # format plesase. could also run rfmt

alias t := test
test:
    # test.

alias w := watch
watch:
    # watch, mostly spin up an application e.g. `r r`-> read log by less/bat/ov/tailspin

alias dep := deploy
deploy:
    # deploy ...like at least commit and push to remote first.

alias sk := seek
seek:
    # seek ...what? maybe reference to other?

[script]
script:
    Write-Host "this is in powershell, without shebang syntax"


[group('dev'),no-cd]
clean:
    uv clean (Split-path -Leaf $pwd)


alias ins := install
[no-cd]
install *args="":
    uv tool install .{{args}}
    
alias uins := uninstall
[script,no-cd]
uninstall:
    uv tool install (Split-path -Leaf $pwd)
