shebang := if os() == 'windows' { 'pwsh.exe' } else { '/usr/bin/env pwsh' }
set shell := ["pwsh", "-c"]
set windows-shell := ["pwsh.exe", "-NoLogo", "-Command"]
set dotenv-load := true
set script-interpreter := ["pwsh.exe", "-NoProfile", "-NoLogo", "-Command"]
# INFO: really dont want to meddle with the .env, direnv is also related to this.
# WARN: should have get them in .gitignore.
set dotenv-filename	:= ".env"
set unstable
set lists
set fallback
# set dotenv-required := true
export JUST_ENV := "just_env" # WARN: this is also a method to export env var. 
_default:
    @just --list
    
alias b := build
[no-cd]
build:
    cargo build --release 

alias bn := build-nightly
[no-cd]
build-nightly:
    cargo +nightly build --release

alias fmt := format
[no-cd]
format args="nothing":
    cargo clippy --all-targets -- -D warnings
    cargo fmt 

# INFO: basic `run` recipe.
alias r := run
default_args := 'args here'
run args=default_args:
    @Write-Host {{default_args}} -ForegroundColor Red

var_test := ""
alias t := test
[no-cd]
test *args=var_test:
    cargo test --test {{args}}

alias bbin := backup-binary
[script]
backup-binary:
    function zqi{
        Invoke-Expression  "zoxide query -i $($args -join " ")"
    }

    cp nightly\zo*\target\release\zoxide.exe "$(zqi scoop zo cur)"
    cp nightly\rip*\target\release\rg.exe "$(zqi rip curr)"
    # cp nightly\tele*\target\release\tv.exe "$(zqi tele curr)"
    cp nightly\hel*\target\opt\hx.exe "$(zqi hel curr)"
    # cp nightly\probe-*\target\release\probe-rs.exe "$(zqi rustup bin)"
    cp nightly\stars*\target\release\starship.exe "$(zqi starship curr)"    

